stages:
  - build
  - deploy

# Job pro sestavení Docker image
build:
  stage: build
  script:
    - echo "Vytvárim Docker image pro frontend..."
    # Použití --no-cache pro vyloučení cache a zajištění správného tagu
    - docker build --no-cache -t frontendgitlab .
  only:
    - frontend
  tags:
    - frontend

deploy:
  stage: deploy
  script:
    - echo "Spouštění Docker containeru pro frontend..."
    - docker run -d -p 421:5173 --name frontend --network proxy frontendgitlab
  only:
    - frontend
  tags:
    - frontend
