stages:
  - smazat
  - build
  - spustit

smazat:
  stage: smazat
  script:
    - echo "Automatické mazání kontejneru a image pro Frontend (Vite) (pokud existuje)..."
    - docker rm -f frontend || true
    - docker image rm -f frontend || true
    - docker volume rm -f frontend || true
  only:
    - frontend
  tags:
    - frontend

build:
  stage: build
  script:
    - echo "Vytvářím Docker image pro Frontend (Vite)..."
    - docker build --no-cache -t frontend .
  only:
    - frontend
  tags:
    - frontend

spustit:
  stage: spustit
  script:
    - echo "Spouštění Docker kontaineru pro Frontend (Vite)..."
    - docker run -d --name frontend --network proxy -v frontend:/app frontend
  only:
    - frontend
  tags:
    - frontend
