stages:
  - build
  - deploy

# Job pro sestavení Docker image
build:
  stage: build
  script:
    - echo "Vytvárím Docker image pro frontend..."
    - docker build -t frontendgitlab .
  only:
    - frontend
  tags:
    - frontend

deploy:
  stage: deploy
  script:
    - echo "Spouštění Docker containeru pro frontend..."
    - docker run -d -p 3000:3000 --name frontend frontendgitlab
  only:
    - frontend
  tags:
    - frontend
