stages:
  - build
  - deploy

# Job pro sestavení Docker image
build:
  stage: build
  script:
    - echo "Vytvárím Docker image pro frontend..."
    - docker build -t frontend-gitlab:$CI_COMMIT_REF_NAME .
  only:
    - frontend  # Job se spustí pouze pro tuto větev
  tags:
    - frontend  # Tento tag musí odpovídat runneru

# Job pro spuštění Docker kontejneru (volitelně)
deploy:
  stage: deploy
  script:
    - echo "Spouštění Docker containeru pro frontend..."
    - docker run -d -p 3000:3000 frontend-gitlab:$CI_COMMIT_REF_NAME
  only:
    - frontend  # Opět, pouze pro tuto větev
  tags:
    - frontend
