version: "3"
services:

    backend:
        container_name: backend-lacehub
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 3000:3000
        depends_on:
            - db

    db:
        container_name: db-lacehub
        image: postgres:14-alpine
        environment:
            POSTGRES_DB: lacehub_local
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: admin
        ports:
            - 5432:5432
        volumes:
            - postgre:/var/lib/postgresql/data

volumes:
    postgre: